### PR TITLE
add my awesome trans

### PR DESCRIPTION
**Pull request by zzz6519003**
original link www.theodo.fr/blog/2016/03/getting-started-with-react-redux-and-immutable-a-test-driven-tutorial-part-1/

### CODE REVIEW

**Comment by zzz6519003** [comment]
see wiki, which enables co-editing

**Comment by island205** [comment]
cool work. please read https://github.com/FrontendMagazine/FrontendMagazine.github.io#欢迎投稿

**Comment by island205** [comment]
请参考我们的投稿指南  https://github.com/FrontendMagazine/FrontendMagazine.github.io#欢迎投稿

**Comment by zzz6519003** [comment]
sorry for interrupting

赵正中

Sent from
https://polymail.io/

On Tue, Apr 26, 2016 at 10:13 PM Zhi Cun

<
mailto:Zhi Cun notifications@github.com

> wrote:

请参考我们的投稿指南
https://github.com/FrontendMagazine/FrontendMagazine.github.io#%E6%AC%A2%E8%BF%8E%E6%8A%95%E7%A8%BF

**Pull request closed without merging**
